build:
  environment:
    variables:
      JWT_SECRET: 'WGKvGsFnXBMb5dXGLHqVBcTUJReRQUumgZQYt8Rmp6XZsHMUMRUzKUDrwAPeBdef'
      JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvZSIsImlhdCI6MTYwMTE1MTM5NSwiZXhwIjoxNjMyNjg3Mzk1fQ.D_mEJZXMQ7XKFPR0y6fECy1tM9YkgP1HuLpIFnbhYuE'
  nodes:
    coverage:
      tests:
        override:
          - command: npm test
            coverage:
              file: coverage/clover.xml
              format: clover